version: "3.8"

services:
  holaflask:
    build: .
    container_name: holaflask
    restart: always # <-- RECOMENDADO: Mantiene tu app encendida siempre
    labels:
      - "traefik.enable=true"
      # Configuración HTTP (Redirección a HTTPS)
      - "traefik.http.routers.holaflask.entrypoints=http"
      - "traefik.http.routers.holaflask.rule=Host(`holaflask.byronrm.com`)"
      - "traefik.http.middlewares.holaflask-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.holaflask.middlewares=holaflask-https-redirect"

      # Configuración HTTPS (Segura)
      - "traefik.http.routers.holaflask-secure.entrypoints=https"
      - "traefik.http.routers.holaflask-secure.rule=Host(`holaflask.byronrm.com`)"
      - "traefik.http.routers.holaflask-secure.tls=true"
      - "traefik.http.routers.holaflask-secure.tls.certresolver=letsencrypt" # <-- AJUSTADO: Cambiar 'http' por tu resolver (ej. letsencrypt)
      - "traefik.http.routers.holaflask-secure.service=holaflask"

      # Puerto interno de Flask y Red de Traefik
      - "traefik.http.services.holaflask.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
